
package Interface;

import domain.Car;
import file.CarFile;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class InsertVehicle extends javax.swing.JFrame {
    
    boolean american;
    

    File file = new File("./car.dat");
    CarFile carfile = new CarFile(file);
    
    public InsertVehicle()throws IOException {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    //método para ingresar el carro
    private void Insert() throws IOException{
        
        Car c = new Car(jTf_Name.getText(),Integer.parseInt(jTf_Year.getText()),
                Integer.parseInt(jTf_SerialNumber.getText()),
                Integer.parseInt(jTf_Mileage.getText()), american);
        
        carfile.addEndRecord(c);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLb_Title = new javax.swing.JLabel();
        jLb_Name = new javax.swing.JLabel();
        jLb_Year = new javax.swing.JLabel();
        jLb_Mileage = new javax.swing.JLabel();
        jLb_SerialNumber = new javax.swing.JLabel();
        jLb_American = new javax.swing.JLabel();
        jRb_Yes = new javax.swing.JRadioButton();
        jRb_No = new javax.swing.JRadioButton();
        jTf_Name = new javax.swing.JTextField();
        jTf_Year = new javax.swing.JTextField();
        jTf_Mileage = new javax.swing.JTextField();
        jTf_SerialNumber = new javax.swing.JTextField();
        jLbl_Image = new javax.swing.JLabel();
        jBtn_Insert = new javax.swing.JButton();
        jBtn_Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLb_Title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLb_Title.setText("Insert Vehicle");
        getContentPane().add(jLb_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 11, -1, 29));

        jLb_Name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLb_Name.setText("Name:");
        getContentPane().add(jLb_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 79, 45, 26));

        jLb_Year.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLb_Year.setText("Year:");
        getContentPane().add(jLb_Year, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 118, -1, -1));

        jLb_Mileage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLb_Mileage.setText("Mileage:");
        getContentPane().add(jLb_Mileage, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 156, -1, -1));

        jLb_SerialNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLb_SerialNumber.setText("Serial Number:");
        getContentPane().add(jLb_SerialNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 194, -1, -1));

        jLb_American.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLb_American.setText("American:");
        getContentPane().add(jLb_American, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 223, -1, 22));

        jRb_Yes.setText("Yes");
        jRb_Yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRb_YesActionPerformed(evt);
            }
        });
        getContentPane().add(jRb_Yes, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 247, -1, -1));

        jRb_No.setText("No");
        jRb_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRb_NoActionPerformed(evt);
            }
        });
        getContentPane().add(jRb_No, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 247, -1, -1));

        jTf_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTf_NameActionPerformed(evt);
            }
        });
        getContentPane().add(jTf_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 83, 129, -1));

        jTf_Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTf_YearActionPerformed(evt);
            }
        });
        getContentPane().add(jTf_Year, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 116, 129, -1));
        getContentPane().add(jTf_Mileage, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 154, 129, -1));
        getContentPane().add(jTf_SerialNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 192, 129, -1));

        jLbl_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Car.png"))); // NOI18N
        getContentPane().add(jLbl_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 250, -1));

        jBtn_Insert.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtn_Insert.setText("Insert");
        jBtn_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_InsertActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn_Insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 290, 102, 32));

        jBtn_Back.setText("Back");
        jBtn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_BackActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 333, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRb_YesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRb_YesActionPerformed
        // TODO add your handling code here:
        american = true;
    }//GEN-LAST:event_jRb_YesActionPerformed

    private void jRb_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRb_NoActionPerformed
        // TODO add your handling code here:
        american = false;
    }//GEN-LAST:event_jRb_NoActionPerformed

    private void jBtn_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_InsertActionPerformed
        // TODO add your handling code here:
        try {
            
            if(carfile.findCar(Integer.parseInt(jTf_SerialNumber.getText())) == false){
            Insert();
            JOptionPane.showMessageDialog(null, "The car has been succesfully entered");
            jTf_Mileage.setText("");
            jTf_Name.setText("");
            jTf_SerialNumber.setText("");
            jTf_Year.setText("");
            }
            else{
                JOptionPane.showMessageDialog(null, "This car already exists", "Error", JOptionPane.ERROR_MESSAGE);
                jTf_Mileage.setText("");
                jTf_Name.setText("");
                jTf_SerialNumber.setText("");
                jTf_Year.setText("");
            }
        } catch (IOException ex) {
            Logger.getLogger(InsertVehicle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtn_InsertActionPerformed

    private void jTf_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTf_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTf_NameActionPerformed

    private void jTf_YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTf_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTf_YearActionPerformed

    private void jBtn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_BackActionPerformed
        try {
            Interface interfaz = new Interface();
            interfaz.close();
            this.setVisible(false);
            interfaz.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger("1"+ex);
        }
        
    }//GEN-LAST:event_jBtn_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InsertVehicle().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(InsertVehicle.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Back;
    private javax.swing.JButton jBtn_Insert;
    private javax.swing.JLabel jLb_American;
    private javax.swing.JLabel jLb_Mileage;
    private javax.swing.JLabel jLb_Name;
    private javax.swing.JLabel jLb_SerialNumber;
    private javax.swing.JLabel jLb_Title;
    private javax.swing.JLabel jLb_Year;
    private javax.swing.JLabel jLbl_Image;
    private javax.swing.JRadioButton jRb_No;
    private javax.swing.JRadioButton jRb_Yes;
    private javax.swing.JTextField jTf_Mileage;
    private javax.swing.JTextField jTf_Name;
    private javax.swing.JTextField jTf_SerialNumber;
    private javax.swing.JTextField jTf_Year;
    // End of variables declaration//GEN-END:variables
}
